//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuto.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAuto.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password..
        /// </summary>
        internal static string AuthenticationIncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("AuthenticationIncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car model name length must not exceed 64 letters..
        /// </summary>
        internal static string ValidationCarModelStringLength {
            get {
                return ResourceManager.GetString("ValidationCarModelStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car plate is required..
        /// </summary>
        internal static string ValidationCarPlateRequired {
            get {
                return ResourceManager.GetString("ValidationCarPlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car plate length must not exceed 10 letters..
        /// </summary>
        internal static string ValidationCarPlateStringLength {
            get {
                return ResourceManager.GetString("ValidationCarPlateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car vendor name length must not exceed 64 letters..
        /// </summary>
        internal static string ValidationCarVendorStringLength {
            get {
                return ResourceManager.GetString("ValidationCarVendorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From is required..
        /// </summary>
        internal static string ValidationConversationFromPlateRequired {
            get {
                return ResourceManager.GetString("ValidationConversationFromPlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From length must not exceed 10 letters..
        /// </summary>
        internal static string ValidationConversationFromPlateStringLength {
            get {
                return ResourceManager.GetString("ValidationConversationFromPlateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required..
        /// </summary>
        internal static string ValidationConversationMessageRequired {
            get {
                return ResourceManager.GetString("ValidationConversationMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message length must not exceed 256 letters..
        /// </summary>
        internal static string ValidationConversationMessageStringLength {
            get {
                return ResourceManager.GetString("ValidationConversationMessageStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To is required..
        /// </summary>
        internal static string ValidationConversationToPlateRequired {
            get {
                return ResourceManager.GetString("ValidationConversationToPlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To length must not exceed 10 letters..
        /// </summary>
        internal static string ValidationConversationToPlateStringLength {
            get {
                return ResourceManager.GetString("ValidationConversationToPlateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length must not exceed 64 letters..
        /// </summary>
        internal static string ValidationEmailStringLength {
            get {
                return ResourceManager.GetString("ValidationEmailStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        internal static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name length must not exceed 64 letters..
        /// </summary>
        internal static string ValidationFirstNameStringLength {
            get {
                return ResourceManager.GetString("ValidationFirstNameStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        internal static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name length must not exceed 64 letters..
        /// </summary>
        internal static string ValidationLastNameStringLength {
            get {
                return ResourceManager.GetString("ValidationLastNameStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login {0} is already in use..
        /// </summary>
        internal static string ValidationLoginIsAlreadyInUse {
            get {
                return ResourceManager.GetString("ValidationLoginIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is required..
        /// </summary>
        internal static string ValidationLoginRequired {
            get {
                return ResourceManager.GetString("ValidationLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login length must be between 6 and 16 letters..
        /// </summary>
        internal static string ValidationLoginStringLength {
            get {
                return ResourceManager.GetString("ValidationLoginStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and its confirmation do not match..
        /// </summary>
        internal static string ValidationPasswordConfirmationCompare {
            get {
                return ResourceManager.GetString("ValidationPasswordConfirmationCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be between 6 and 16 letters..
        /// </summary>
        internal static string ValidationPasswordStringLength {
            get {
                return ResourceManager.GetString("ValidationPasswordStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone length must not exceed 12 letters..
        /// </summary>
        internal static string ValidationPhoneStringLength {
            get {
                return ResourceManager.GetString("ValidationPhoneStringLength", resourceCulture);
            }
        }
    }
}
