//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuto.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_History
    {
        public int MessageID { get; set; }
        public Nullable<int> RecieverId { get; set; }
        public Nullable<System.DateTime> DateViewed { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
