//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuto.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MessageText { get; set; }
        public byte[] MsgPhoto { get; set; }
        public string GPSCoordinates { get; set; }
        public string CarRegNumber { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public Nullable<bool> Score { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CarOwner CarOwner { get; set; }
        public virtual Message_History Message_History { get; set; }
    }
}
